CREATE TABLE Entite (
    code_entite INT(7) NOT NULL AUTO_INCREMENT,
    raison_sociale VARCHAR(30) NOT NULL,
    nom_commercial VARCHAR(30),
    logo VARCHAR(200),
    siret BIGINT(14),
    code_ape CHAR(5),
    code_rna CHAR(10),
    code_cee CHAR(13),
    code_societe_appartenance INT(6) NOT NULL,
    adresse TEXT NOT NULL,
    telephone VARCHAR(12),
    mail VARCHAR(50),
    site_internet VARCHAR(255),
    commentaires VARCHAR(200),
    code_type_entite CHAR(4) NOT NULL,
    code_type_don CHAR(4),
    code_type_produit CHAR(4),
    code_type_competence CHAR(4),
    commentaires_logistique VARCHAR(200),
    presence_quai ENUM('O','N'),
    pieces_associees VARCHAR(200),
    cerfa ENUM('O','N'),
    code_frequence_cerfa CHAR(4),
    date_arret_activite DATE,
    PRIMARY KEY (code_entite),
    FOREIGN KEY (code_type_entite) REFERENCES TypesEntites(code_type_entite) ON UPDATE CASCADE,
    FOREIGN KEY (code_type_don) REFERENCES TypesDons(code_type_don) ON UPDATE CASCADE,
    FOREIGN KEY (code_type_produit) REFERENCES TypesProduits(code_type_produits) ON UPDATE CASCADE,
    FOREIGN KEY (code_type_competence) REFERENCES TypesCompetences(code_type_competence) ON UPDATE CASCADE,
    FOREIGN KEY (code_frequence_cerfa) REFERENCES FrequencesCerfa(code_frequence_cerfa) ON UPDATE CASCADE,
    FOREIGN KEY (code_societe_appartenance) REFERENCES Entreprise(code_Societe) ON UPDATE CASCADE ON DELETE CASCADE
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
