CREATE TABLE Dons (
    code_Don INT AUTO_INCREMENT,
    titre_don VARCHAR(50) NOT NULL,
    code_Entite_donatrice INT(7),
    date_proposition_don DATE NOT NULL,
    code_contact_Entite_donatrice INT,
    code_type_don CHAR(4) NOT NULL,
    code_type_competences CHAR(4),
    code_type_produits CHAR(4),
    code_mode_conservation_produits CHAR(4),
    date_debut_mise_disposition DATE,
    date_fin_mise_disposition DATE,
    commentaires VARCHAR(200),
    pieces_associees VARCHAR(200),
    code_Utilisateur_saisie_don INT,
    statut_acceptation_don ENUM('V', 'R', 'A'),
    date_acceptation_refus_don DATE,
    code_Utilisateur_accepte_refuse_don INT,
    code_site_beneficiaire_don INT,
    indicateur_remerciement ENUM('O','N'),
    date_remerciement DATE,
    nom_destinataire_cerfa VARCHAR(50),
    adresse_destinataire_cerfa VARCHAR(100),
    adresse_mail_destinataire_cerfa VARCHAR(100),
    telephone_destinataire_cerfa VARCHAR(12),
    valeur_cerfa DECIMAL(10,2),
    cerfa_fait ENUM('O','N'),
    date_cerfa DATE,
    cerfa VARCHAR(200),
    PRIMARY KEY (code_Don),
    FOREIGN KEY (code_Entite_donatrice) REFERENCES Entite(code_Entite) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (code_contact_Entite_donatrice) REFERENCES Contacts(code_contact) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (code_type_don) REFERENCES TypesDons(code_type_don) ON UPDATE CASCADE,
    FOREIGN KEY (code_type_competences) REFERENCES TypesCompetences(code_type_competence) ON UPDATE CASCADE,
    FOREIGN KEY (code_type_produits) REFERENCES TypesProduits(code_type_produits) ON UPDATE CASCADE,
    FOREIGN KEY (code_mode_conservation_produits) REFERENCES ModeConservationProduits(code_mode_conservation_produits) ON UPDATE CASCADE,
    FOREIGN KEY (code_Utilisateur_saisie_don) REFERENCES Utilisateurs(code_utilisateur) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (code_Utilisateur_accepte_refuse_don) REFERENCES Utilisateurs(code_utilisateur) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (code_site_beneficiaire_don) REFERENCES Sites(code_site) ON UPDATE CASCADE ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;