CREATE TABLE ModalitesLivraison (
    numero_livraison INT AUTO_INCREMENT,
    code_Don INT NOT NULL,
    code_type_livraison CHAR(3) NOT NULL,
    date_prevue_livraison DATE NOT NULL,
    heure_prevue_livraison TIME,
    adresse_enlevement VARCHAR(255),
    civilite_contact_enlevement VARCHAR(3),
    nom_contact_enlevement VARCHAR(20),
    prenom_contact_enlevement VARCHAR(20),
    telephone_contact_enlevement VARCHAR(12),
    mail_contact_enlevement VARCHAR(255),
    code_Prestataire_transporteur INT,
    adresse_livraison VARCHAR(255) NOT NULL,
    civilite_contact_livraison VARCHAR(3),
    nom_contact_livraison VARCHAR(20),
    prenom_contact_livraison VARCHAR(20),
    telephone_contact_livraison VARCHAR(12),
    mail_contact_livraison VARCHAR(255),
    nombre_palettes_prevu VARCHAR(10),
    nombre_palettes_consignees_prevu VARCHAR(10),
    nombre_cartons_prevu VARCHAR(10),
    poids_prevu_kg VARCHAR(10),
    produits_sur_palettes ENUM('O', 'N'),
    temperature_conserv_produits VARCHAR(3),
    commentaires VARCHAR(200),
    pieces_associees VARCHAR(200),
    PRIMARY KEY (numero_livraison),
    FOREIGN KEY (code_Don) REFERENCES Dons(code_Don) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (code_type_livraison) REFERENCES TypeLivraison(code_type_livraison) ON UPDATE CASCADE,
    FOREIGN KEY (code_Prestataire_transporteur) REFERENCES Prestataires(code_Prestataire) ON UPDATE CASCADE ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;